### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by raybellis** [OpenVPN/puppet-openvpnas#1]
I was hoping to use this module to control the users on our OpenVPN AS (configured to use Kerberos passwords) but it's currently missing some necessary functionality.

Management of properties such as `type` doesn't work correctly because OpenVPN AS automagically sets the value to `user_connect` or `user_compile`, with no way to read in advance which value it already has.

Ideally I want to be able to actually create and remove users, but that feature doesn't exist yet.  I've never yet written a Puppet type in Ruby, but having read the code for the current module I'd be happy to help write and test an `openvpas_user` type.

Please let me know how I can help!

**Comment by sahaqaa** [comment]
Closing this thread, It was resolved by @raybellis in https://github.com/OpenVPN/puppet-openvpnas/pull/6
